Repository nixon-voxell/lumina, pull requests merged in 2024-10, with the labels that each got.

#29 Braking & boost system and fixes jittering/flickering issue
  assets/levels/Lobby.glb
  assets/registry.json
  blender/Lobby.blend
  network_settings.ron
  src/client.rs
  src/client/camera.rs
  src/client/effector.rs
  src/client/local_lobby.rs
  src/client/player.rs
  src/protocol.rs
  src/server/lobby.rs
  src/server/player.rs
  src/shared.rs
  src/shared/input.rs
  src/shared/physics.rs
  src/shared/player.rs
Labels: bug, enhancement, dev

#17 Procedural rectangle spawn implementation
  assets/registry.json
  src/client/multiplayer_lobby.rs
  src/server/lobby.rs
  src/shared.rs
  src/shared/procedural_map.rs
  src/shared/procedural_map/grid_map.rs
  src/shared/procedural_map/random_walk_cave.rs
Labels: enhancement, dev

#39 Terrain collision
  crates/lumina_server/src/lobby.rs
  crates/lumina_shared/src/procedural_map.rs
  crates/lumina_shared/src/procedural_map/grid_map.rs
Labels: dev
