Repository nixon-voxell/lumina, pull requests merged in 2025-02, with the labels that each got.

#106 Spaceship model import
  Cargo.lock
  assets/levels/spaceships/AssassinCollider.glb
  assets/levels/spaceships/AssassinCollider.meta.ron
  assets/levels/spaceships/AssassinConfig.assets.ron
  assets/levels/spaceships/AssassinConfig.glb
  assets/levels/spaceships/AssassinVisual.assets.ron
  assets/levels/spaceships/AssassinVisual.glb
  assets/levels/spaceships/DefenderCollider.glb
  assets/levels/spaceships/DefenderCollider.meta.ron
  assets/levels/spaceships/DefenderConfig.glb
  assets/levels/spaceships/DefenderConfig.meta.ron
  assets/levels/spaceships/DefenderVisual.glb
  assets/levels/spaceships/DefenderVisual.meta.ron
  assets/materials/AssassinBlack1.glb
  assets/materials/AssassinBlack2.glb
  assets/materials/AssassinGray1.glb
  assets/materials/AssassinGray2.glb
  assets/materials/AssassinYellow1.glb
  assets/materials/AssassinYellow2.glb
  assets/materials/AssassinYellow3.glb
  assets/materials/DefenderBlack1.glb
  assets/materials/DefenderBlue1.glb
  assets/materials/DefenderBlue2.glb
  assets/materials/DefenderBlue3.glb
  assets/materials/DefenderBlue4.glb
  assets/materials/DefenderBlue5.glb
  assets/materials/DefenderDarkBlue1.glb
  assets/materials/DefenderDarkBlue2.glb
  assets/registry.json
  assets/shaders/radiance_cascades/radiance_cascades.wgsl
  blender/Spaceships.blend
  crates/bevy_radiance_cascades/src/radiance_cascades.rs
  crates/lumina_client/src/player/spaceship.rs
  crates/lumina_client/src/player/weapon.rs
  crates/lumina_client/src/screens/local_lobby.rs
  crates/lumina_common/src/blueprint_type.rs
  crates/lumina_common/src/blueprint_visual.rs
  crates/lumina_common/src/lib.rs
  crates/lumina_common/src/physics.rs
  crates/lumina_common/src/type_registry.rs
  crates/lumina_shared/src/blueprint_collider.rs
  crates/lumina_shared/src/blueprints.rs
  crates/lumina_shared/src/lib.rs
  crates/lumina_shared/src/protocol.rs
  crates/lumina_shared/src/type_registry.rs
  crates/lumina_vfx/Cargo.toml
  crates/lumina_vfx/src/particle.rs
Labels: enhancement, dev, art

#119 Spaceship abilities
  Cargo.lock
  assets/icons/dash.svg
  assets/icons/heal.svg
  assets/icons/health.svg
  assets/icons/shadow.svg
  assets/levels/spaceships/AssassinConfig.glb
  assets/levels/spaceships/DefenderConfig.glb
  assets/registry.json
  assets/shaders/radiance_cascades/composite.wgsl
  assets/shaders/vfx/heal_ability.wgsl
  assets/shaders/vfx/portal.wgsl
  assets/typst/client/spaceship_stats.typ
  blender/Spaceships.blend
  crates/bevy_radiance_cascades/examples/rc_debug.rs
  crates/lumina_client/src/camera.rs
  crates/lumina_client/src/lib.rs
  crates/lumina_client/src/player/spaceship.rs
  crates/lumina_client/src/screens/local_lobby.rs
  crates/lumina_client/src/ui/game_mode.rs
  crates/lumina_client/src/ui/game_ui/spaceship_stats.rs
  crates/lumina_client/src/ui/spaceship_select.rs
  crates/lumina_common/src/convert_3d_to_2d.rs
  crates/lumina_common/src/lib.rs
  crates/lumina_common/src/physics.rs
  crates/lumina_shared/src/action.rs
  crates/lumina_shared/src/player.rs
  crates/lumina_shared/src/player/spaceship.rs
  crates/lumina_shared/src/player/spaceship/ability.rs
  crates/lumina_shared/src/player/spaceship/movement.rs
  crates/lumina_shared/src/protocol.rs
  crates/lumina_shared/src/type_registry.rs
  crates/lumina_vfx/.gitignore
  crates/lumina_vfx/Cargo.toml
  crates/lumina_vfx/examples/material_2d.rs
  crates/lumina_vfx/src/lib.rs
  crates/lumina_vfx/src/material2d.rs
  crates/lumina_vfx/src/type_registry.rs
  create_asset_junctions.bat
Labels: enhancement, dev

#124 Sandbox ui
  Cargo.lock
  assets/materials/SpotlightGlow.glb
  assets/registry.json
  assets/shaders/vfx/heal_ability.wgsl
  assets/typst/client/sandbox.typ
  blender/Lobbies.blend
  crates/lumina_client/Cargo.toml
  crates/lumina_client/src/lib.rs
  crates/lumina_client/src/screens/in_game.rs
  crates/lumina_client/src/screens/multiplayer_lobby.rs
  crates/lumina_client/src/screens/sandbox.rs
  crates/lumina_client/src/ui.rs
  crates/lumina_client/src/ui/lobby.rs
  crates/lumina_client/src/ui/sandbox.rs
  crates/lumina_server/Cargo.toml
  crates/lumina_server/src/lobby.rs
  crates/lumina_server/src/lobby/matchmaking.rs
  crates/lumina_server/src/lobby/sandbox.rs
  crates/lumina_shared/Cargo.toml
  crates/lumina_shared/src/lib.rs
  crates/lumina_shared/src/player/ammo.rs
  crates/lumina_shared/src/player/spawn_point.rs
Labels: dev, design
